### PR TITLE
Use kjobctl printcrd command to apply CRDs.

### PR DESCRIPTION
**Pull request by mbobrovskyi**
## Fixes / Features
- Use kjobctl printcrd command to apply CRDs.

## Special notes for your reviewer:
It's better to apply CRDs with version of kjobctl.

## Testing / Documentation
Testing details.

- [ y/n ] Tests pass
- [ y/n ] Appropriate changes to documentation are included in the PR

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
> Please switch to local branch, we are not using forks now

Should I recreate PRs?

**Comment by pawloch00** [comment]
> > Please switch to local branch, we are not using forks now
> 
> @pawloch00 Should I recreate PRs?

I am not sure, but probably yes

**Comment by mbobrovskyi** [comment]
> > > Please switch to local branch, we are not using forks now
> > 
> > 
> > @pawloch00 Should I recreate PRs?
> 
> I am not sure, but probably yes, same applies for other PRs

ERROR: Permission to AI-Hypercomputer/xpk.git denied to mbobrovskyi.
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.

**Comment by pawloch00** [comment]
Ok, I will take a look into it and will come back here, let's leave it as it is now

**Comment by mbobrovskyi** [comment]
cc @mwysokin

**Comment by mbobrovskyi** [comment]
cc @IrvingMg

**Comment by mbobrovskyi** [comment]
/close 

Due to switching to local branch. 
https://github.com/AI-Hypercomputer/xpk/pull/234

**Comment by mbobrovskyi** [comment]
/close 

Due to switching to local branch. 
https://github.com/AI-Hypercomputer/xpk/pull/234

**Pull request closed without merging**
