### PR TITLE
Bump Kueue version from 0.8.1 to 0.9.1

### PR DESCRIPTION
**Pull request by mbobrovskyi**
## Fixes / Features
- Bump Kueue version from 0.8.1 to 0.9.1.

## Testing / Documentation
Testing details.

- [ y/n ] Tests pass
- [ y/n ] Appropriate changes to documentation are included in the PR

### CODE REVIEW

**Comment by mbobrovskyi** [comment]
cc @pawloch00 @IrvingMg

**Comment by pawloch00** [comment]
cc @44past4

**Comment by pawloch00** [comment]
Please mark this PR as do not merge. It is waiting for decision to update kueue

**Comment by pawloch00** [comment]
just write [Do not merge] it title or sth

**Comment by pawloch00** [comment]
Please test it and if everything seems fine it can be merged

**Comment by mbobrovskyi** [comment]
@BluValor @IrvingMg Could you please take a look?

**Review by IrvingMg — APPROVED** [review]

**Review by pawloch00 — APPROVED** [review]

**Pull request merged**
